package com.jianye.spring.entity;
// Generated 2016-6-10 20:00:42 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserInfoSsh generated by hbm2java
 */
@Entity
@Table(name = "user_info_ssh", catalog = "shop")
public class UserInfoSsh implements java.io.Serializable {

	private Integer id;
	private Integer age;
	private String name;
	private String telephone;

	public UserInfoSsh() {
	}

	public UserInfoSsh(String name) {
		this.name = name;
	}

	public UserInfoSsh(Integer age, String name, String telephone) {
		this.age = age;
		this.name = name;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
